spring.application.name=OrganizationService
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/doggyapp
spring.datasource.username=doggyapp
spring.datasource.password=doggyapp

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false